apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mt1hef-yr-python
  janus-idp.io/tekton: mt1hef-yr-python
  backstage.io/kubernetes-id: mt1hef-yr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mt1hef-yr-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
