apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: mt1hef-yr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mt1hef-yr-python 
  name: mt1hef-yr-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mt1hef-yr-python
    weight: 100 
