apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mt1hef-yr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mt1hef-yr-python 
  name: mt1hef-yr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mt1hef-yr-python 
